// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL2lKXndmAVdtalESYvl-B8BBJ9G6aPdM',
    appId: '1:707616392800:web:83aa2d0ccf732555166505',
    messagingSenderId: '707616392800',
    projectId: 'mayorapp-74460',
    authDomain: 'mayorapp-74460.firebaseapp.com',
    storageBucket: 'mayorapp-74460.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8Gr0vQlfIAS9PQ8jy0QetpCzCrp7KIM',
    appId: '1:707616392800:android:b62b5b6e7053f0d7166505',
    messagingSenderId: '707616392800',
    projectId: 'mayorapp-74460',
    storageBucket: 'mayorapp-74460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR95VzcG-_E1L0M0kCNB-oI0KLK0dkL2U',
    appId: '1:707616392800:ios:128bc7184c62e46d166505',
    messagingSenderId: '707616392800',
    projectId: 'mayorapp-74460',
    storageBucket: 'mayorapp-74460.appspot.com',
    iosBundleId: 'com.municipality.mayorapp',
  );
}
